services:
  backend:
    image: musicback2
    ports:
      - "3000:3000"  # Host:Container
    environment:
      - AWS_ACCESS_KEY_ID = 
      - AWS_SECRET_ACCESS_KEY= 
      - AWS_REGION= 
      - S3_BUCKET_NAME= 
      
    networks:
      - audiox-network

  frontend:
    image: musicfront2
    ports:
      - "5173:5173"  
    networks:
      - audiox-network

networks:
  audiox-network:
    driver: bridge